# Generated by Django 6.0.8 on 2026-10-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Arduino", "Arduino"),
                            ("Robotics", "Robotics"),
                            ("Home Automation", "Home Automation"),
                            ("IoT", "IoT"),
                            ("Sensors", "Sensors"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "components",
                    models.TextField(help_text="Comma-separated components"),
                ),
                ("working", models.TextField()),
                ("circuit_diagram", models.URLField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                ("source_code", models.TextField(blank=True)),
                ("difficulty", models.CharField(default="Beginner", max_length=30)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
